### ISSUE TITLE
Unable to extend plugin due to use of pre-built lib OSHealthFitnessLib

### ISSUE THREAD

**Issue by apank** [OutSystems/cordova-outsystems-healthfitness#81]
In it's current state there is only a limited amount of features;

I wanted to fork this repo and add new features but am unable to because OSHealthFitnessLib is already compiled.

Can you please change that so others can extend the features of this plugin.

**Comment by OS-ricardomoreirasilva** [comment]
Hey @apank. Apologies for the late reply.

Is your concern regarding a specific Operating System?
